### ISSUE TITLE
404 error when accessing https://covid19.quebec.ca/PreuveVaccinaleApi/issuer/.well-known/jwks.json

### ISSUE THREAD

**Issue by Stavr0** [obrassard/shc-extractor#3]
Tried with a QR that was produced on July 28.

_out/_ contents.

` "payload": {         "iss": "https://covid19.quebec.ca/PreuveVaccinaleApi/issuer"  ` 

`    "verifications": {  "trustable": false   }`

```
curl -i https://covid19.quebec.ca/PreuveVaccinaleApi/issuer
HTTP/1.1 404 Not Found
Request-Context: appId=cid-v1:83d2d660-f9fc-4bf4-8f8d-c14090c51237
Strict-Transport-Security: max-age=15724800; includeSubDomains
X-Cache: CONFIG_NOCACHE
X-Azure-Ref: 0EO0CYQAAAAB7H9RvofX1TJ6Tt3IXqjSyWU1RMDFFREdFMDkxMgA5YTcwM2E4NS1mYTQ1LTQyNWYtYTE0NC00NDQ3ZTZhMDc0ZGY=
Date: Thu, 29 Jul 2021 18:01:51 GMT
Content-Length: 0
```

**Comment by obrassard** [comment]
Hello @Stavr0, has explained here : #2 , according to the Smart Health Cards standard, the public keys required to validate the trustworthiness of the data should be published at `{issuer}/.well-known/jwks.json` (with `{issuer}` corresponding to the `iss` field in the payload). However, it seems that the government has not published those keys, probably to avoid that anybody starts validating QR codes.

 Knowing this,  it is not an issue that the server returns `"trustable": false` since we cannot get the keys, we cannot ensure the QR code's data is trustable.

Have a nice day !

**Comment by Stavr0** [comment]
... and I just noticed no less than 2 other issues for this very problem.   :)

**Comment by obrassard** [comment]
Dont worry ☺️
